Allow write_file to sanitize spaces and newlines
ansible-community/antsibull-core pull request #165
Opened 2024-08-20 09:30 UTC by ssbarnea

Needed-By: https://github.com/ansible-community/antsibull-docs/issues/305

2024-08-20 12:45 UTC, felixfontein requested changes
I think this is the wrong place for such functionality. This should be done by the caller before calling `write_file()`.

Also the implementation is very inefficient. Check for example with `" "*100000 + "x" + " "*100000`. Compare for example to `content = '\n'.join([l.rstrip(' \t') for l in content.splitlines()])`, which is *so* much faster for this example.

2024-08-20 19:39 UTC, gotmax23 commented on src/antsibull_core/utils/io.py
> +    filename: StrOrBytesPath, content: str, /, sanitize: bool = False
Technically speaking, making `filename` and `content` positional-only arguments is a breaking change.

2024-08-20 19:39 UTC, gotmax23 commented on src/antsibull_core/utils/io.py
> +        content = content.rstrip("\n\r") + "\n"
I agree with Felix that perhaps this isn't the best place to do this, but maybe a separate `sanitize_trailing_spaces()` function in antsibull_core would make sense

2024-08-20 19:39 UTC, gotmax23 commented on changelogs/fragments/165-write-file-sanitize.yml
> +  - Allow write_file to sanitize spaces and newlines. (https://github.com/ansible-community/antsibull-docs/issues/305)
```suggestion
  - Allow write_file to sanitize spaces and newlines (https://github.com/ansible-community/antsibull-docs/issues/305).
```

is the format we generally follow.

2024-09-22 15:56 UTC, gotmax23 commented
Is this still relevant? I think @ssbarnea's original issue was solved differently in antsibull-docs?

2024-09-22 15:57 UTC, gotmax23 commented
Either way, thank you for the contribution.

2024-11-03 11:47 UTC, felixfontein commented
Closing since this is apparently no longer needed. Thanks for your contribution!

2024-11-03 11:47 UTC, closed without merging